### ISSUE TITLE
מבנה הגייסון של ליאור

### ISSUE THREAD

**Issue by goolime** [ArielMannes/MTGDeckBot#12]
fetuers list
fetuers to cards multivers id
cards{
	id= multiversid
	name= english only
	cmc= symbols(RGBUW)+free mana (standart notions)
	power=int -none creturs will be negative
	toughness=
	type=as on cards
	(subtype as feature)
	(legendary= as feature)
	features= list of features reducted by famileis
	vanila value= double
}
sinergy table= card x is played when y is on the battle field

**Comment by lior-ashiri** [comment]
יש להוסיף רשימה של כל הsplit cards בסטנדרט

יש למנוע מהמערכת להוסיף לקובץ "סטנדרט" את רשימת הקלפים האסורים...
