### ISSUE TITLE
לתקן את חילוץ הפיצ'רים

### ISSUE THREAD

**Issue by lior-ashiri** [ArielMannes/MTGDeckBot#32]
הנה דוגמא נגדית לבאג:
עבור הקלף "Danitha Capashen, Paragon", אמור לחזור פלט המכיל את המילים first strike, lifelink vigilance
כרגע זה לא חוזר עם הפלט הזה....

**Comment by ArielMannes** [comment]
take the two cards - write tests for them - fix the issues
